package com.fiskrindy.jpaDemo.models;

import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Entity
@Table(name="books")
public class Book {
	
//		"Id of type long - The id will be the primary key for each individual book we create"
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
//	    The title & the different validations cannot be Null & must have a size within 5-200 characters
    @NotNull
    @Size(min = 5, max = 200)
    private String title;
    
//	    The description & the different validations cannot be Null & must have a size within 5-200 characters
    @NotNull
    @Size(min = 5, max = 200)
    private String description;
    
//	    The language & the different validations cannot be Null & must have a size within 3-40 characters
    @NotNull
    @Size(min = 3, max = 40)
    private String language;
    
//	    The pages & the different validations cannot be Null & must have a minimum of 100 pages
    @NotNull
    @Min(100)
    private Integer numberOfPages;
    // This will not allow the createdAt column to be updated after creation
    
//	    Created at & Updated at - Created at Column can never be changed or updated - it is constant
    @Column(updatable=false)
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date createdAt;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date updatedAt;
  
//	    Constructors - 1 must be empty with no parameters & the other one has a signature (select parameters)
    public Book() {
    }
    public Book(String title, String description, String lang, int pages) {
        this.title = title;
        this.description = description;
        this.language = lang;
        this.numberOfPages = pages;
    }
    
//	    Created At - One time only
    @PrePersist
    protected void onCreate(){
        this.createdAt = new Date();
    }
    
//	    Updated At - every time date stamped
    @PreUpdate
    protected void onUpdate(){
        this.updatedAt = new Date();
    }
    
//	    AutoGenerated Getters & Setters
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getLanguage() {
		return language;
	}
	public void setLanguage(String language) {
		this.language = language;
	}
	public Integer getNumberOfPages() {
		return numberOfPages;
	}
	public void setNumberOfPages(Integer numberOfPages) {
		this.numberOfPages = numberOfPages;
	}
	public Date getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	public Date getUpdatedAt() {
		return updatedAt;
	}
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}

